DELETE FROM COINS;
INSERT INTO COINS (DENOMINATION, QUANTITY) VALUES (0.01, 100);
INSERT INTO COINS (DENOMINATION, QUANTITY) VALUES (0.05, 100);
INSERT INTO COINS (DENOMINATION, QUANTITY) VALUES (0.10, 100);
INSERT INTO COINS (DENOMINATION, QUANTITY) VALUES (0.25, 100);